spring:
  application:
    name: spring-cloud-zuul

server:
  port: 8888
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
zuul:
  routes:
    web:
      path: /web/**
      serviceId: spring-boot-web-app
    api-1: 
      path: /consumer/**
      serviceId: spring-cloud-consumer
  #是否开启重试功能
  retryable: false #true
  
ribbon: 
  #对当前服务的重试次数
  MaxAutoRetries: 2
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0