spring:
  application:
    name: spring-cloud-eureka

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/  #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔
    register-with-eureka: false  #表示是否将自己注册到Eureka Server，默认为true
    fetch-registry: false  #表示是否从Eureka Server获取注册信息，默认为true
  server:
    #关闭保护机制，这样可以确保注册中心中不可用的实例被及时的剔除（不推荐）
    #enable-self-preservation: false 
    #enableSelfPreservation: false
    renewalPercentThreshold: 0.49
    
  