server:
  port: 8010
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lori01/spring-cloud-demo/     # 配置git仓库的地址
          search-paths: config-server/src/main/resources                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: sephy9527@qq.com                                        # git仓库的账号
          password: qq865860018+-                                    # git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/   ## 注册中心eurka地址
